name: Build and scan Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: sysdig/actions@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag BagyaShivani/sysdig:latest
    - name: Scan image
      uses: BagyaShivani/scan-action@v1
      with:
        image-tag: "BagyaShivani/sysdig:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
    - name: Sysdig Secure Inline Scan
      uses: BagyaShivani/scan-action@v1
      with:
        # Tag of the image to analyse
        image-tag:  "BagyaShivani/sysdig:latest"
        # API token for Sysdig Scanning auth
        sysdig-secure-token:  ${{ secrets.SYSDIG_SECURE_TOKEN }}
        
 

 
 
   
