name: Build and scan Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest
    - name: Scan image
      uses: sysdiglabs/scan-action@v1
      with:
        image-tag: "sysdiglabs/dummy-vuln-app:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
    - name: Sysdig Secure Inline Scan
      uses: sysdiglabs/scan-action@v1
      with:
        # Tag of the image to analyse
        image-tag:  "sysdiglabs/dummy-vuln-app:latest"
        # API token for Sysdig Scanning auth
        sysdig-secure-token:  ${{ secrets.SYSDIG_SECURE_TOKEN }}
        
 

 
 
   
